env:
  global:
  - secure: S/riGHQi2yaqq8/ZSogfLQ4+R+CoIkOsalC17j/d2BNRMLEAjUCNV7k4QFA+B3cBUrlsFlP2qA19NX63nirYGDitfgUxGLBL9i6qZNbT/hCtcVymei8m6CSwIuxPkNSTb/+1k+TYFGFG7zxlsPUgMA78L2onOzI3OSQAbBuWgm4=
language: c
before_install:
- curl -OL http://raw.github.com/OHI-Science/ohi-webapps/master/ohi-travis-tool.sh
- chmod 755 ./ohi-travis-tool.sh
script:
- echo GIT_NAME:"${GIT_NAME}"
- echo GIT_EMAIL:"${GIT_EMAIL}"
- echo TRAVIS_COMMIT:"${TRAVIS_COMMIT}"
- echo GH_TOKEN:"${GH_TOKEN}"
- echo TRAVIS_REPO_SLUG:"${TRAVIS_REPO_SLUG}"
- echo 'test' > testing.txt
after_success:
- ./ohi-travis-tool.sh push_changes
notifications:
  email:
    recipients:
    - bbest@nceas.ucsb.edu
    - bbest@nceas.ucsb.edu
    on_success: change
    on_failure: always
